### PR TITLE
Add example module (simple SSA lang)

### PR DESCRIPTION
**Pull request by raehik**
Adapted from the 2017 unpublished paper's repo.

### CODE REVIEW

**Comment by raehik** [comment]
Ah! The example was already adapted for the test spec. I'll refactor a bit so the test doesn't redefine the example code.

**Comment by raehik** [comment]
This needs a review before merging. Notable changes:

  * Promoted input source existential type to type variable in `Reprinting`.
  * Example module added, adapted from sample code from the unpublished paper, and the tests. Blog-style literate Haskell file. I'm aware that I've attempted to explain something I didn't write and haven't used much, so it will need some working.
  * Tests cleaned up, now uses example module.

**Comment by raehik** [comment]
Needs rebasing to clean up before merge! Leaving that until after reviews & edits though.

**Comment by raehik** [comment]
Rebased, now just the `Reprinting` change followed by the example module.

**Comment by dorchard** [comment]
Okay- it's on my todo list to check this.

**Comment by dorchard** [comment]
Okay I have done a pass over this and added a few things and tweaked a few other bits. Please check that you are happy with them! I note there are still a couple of TODOs.

**Comment by raehik** [comment]
Thanks! I didn't understand the evaluate-add-as-comment reprinter until I reread it today. The other to-do was realising I needed to introduce SYB but had ignored it previously. I can clean those up acceptably.

**Comment by raehik** [comment]
I've a better understanding of what & why `genReprintings` is now. I've rewritten that part [(diff#L214)](https://github.com/camfort/reprinter/pull/4/commits/22e611fe61a5aad691ecfd65fbf898ad20189b80#diff-a0162e9d97be552a021e0d14714c5cdedc55a93b1a12945f6409b8d0cfbd8931L214) and added simple commentary on the comment reprinter. If you're happy with the changes, I think it's good to merge.

**Pull request merged**
